TYPO3:
  TYPO3CR:
    contentDimensions:
      'language':
        # The default dimension that is applied when creating nodes without specifying a dimension
        default: 'en'
        # The default preset to use if no URI segment was given when resolving languages in the router
        defaultPreset: 'en'
        label: 'Language'
        icon: 'icon-language'
        presets:
          'en':
            label: 'English'
            values: ['en']
            uriSegment: 'en'
          'de':
            label: 'Deutsch'
            values: ['de']
            uriSegment: 'de'
